INSERT INTO GENRES VALUES (1, 'Fantasy');
INSERT INTO GENRES VALUES (2, 'Science Fiction');
INSERT INTO GENRES VALUES (3, 'Romance');
INSERT INTO GENRES VALUES (4, 'Thriller');
INSERT INTO GENRES VALUES (5, 'Mystery');
INSERT INTO GENRES VALUES (6, 'Adventure');
